#!/usr/bin/env ruby

repos = `ghq list`.lines.map(&:chop)

ghq_root = `ghq root`.chop

repos.each do |repo|
  Dir.chdir(File.expand_path("#{ghq_root}/#{repo}")) do
    next unless Dir.exist?('.git')

    puts repo if system('git branch | grep -q master > /dev/null 2>&1')
  end
end
